# Reference-to-current drift detection

`ConDrift` and `CatDrift` compare individual vectors. Their analyzers fit one independent detector per ID in a panel. The current population is supplied explicitly, so no time column or temporal window is required.

In [2]:
import sys
import os
sys.path.append(os.path.abspath("../.."))
import numpy as np
import pandas as pd

from tinyshift.drift import (
    CatDrift,
    CategoricalDriftAnalyzer,
    ConDrift,
    ContinuousDriftAnalyzer,
)

rng = np.random.default_rng(42)

## 1. `ConDrift`: continuous vectors

The normalized Wasserstein score expresses change in units of reference standard deviation. The bootstrap threshold is calibrated from the reference for the current sample size.

In [3]:
continuous_reference = rng.normal(0.0, 1.0, 500)
continuous_current = rng.normal(1.0, 1.2, 100)

continuous_detector = ConDrift(
    metric="wasserstein",
    threshold="bootstrap",
    normalize=True,
    n_resamples=300,
    random_state=42,
).fit(continuous_reference)
continuous_detector.predict(continuous_current)

DriftResult(score=0.9472812345679126, threshold=0.23266868321132672, drift=True, reference_size=500, current_size=100)

## 2. `CatDrift`: categorical vectors

Categorical supports are aligned over their union, so a new category contributes to the score. Metrics available are `jensen_shannon`, `psi`, and `chebyshev`.

In [4]:
categorical_reference = rng.choice(
    ["free", "standard", "premium"], 500, p=[0.60, 0.30, 0.10]
)
categorical_current = rng.choice(
    ["free", "standard", "premium", "enterprise"],
    100,
    p=[0.20, 0.35, 0.25, 0.20],
)

categorical_detector = CatDrift(
    metric="jensen_shannon",
    threshold="bootstrap",
    n_resamples=300,
    random_state=42,
).fit(categorical_reference)
categorical_detector.predict(categorical_current)

DriftResult(score=0.3580419344022656, threshold=0.0922209719731288, drift=True, reference_size=500, current_size=100)

## 3. `ContinuousDriftAnalyzer`: continuous panel

Each current ID is compared only with its own fitted reference population. Here `store_A` shifts while `store_B` remains stable.

In [5]:
continuous_reference_panel = pd.DataFrame({
    "unique_id": np.repeat(["store_A", "store_B"], 300),
    "y": np.r_[rng.normal(0, 1, 300), rng.normal(10, 2, 300)],
})
continuous_current_panel = pd.DataFrame({
    "unique_id": np.repeat(["store_A", "store_B"], 80),
    "y": np.r_[rng.normal(2.5, 1, 80), rng.normal(10, 2, 80)],
})

continuous_analyzer = ContinuousDriftAnalyzer(
    ConDrift(n_resamples=300, random_state=42)
).fit(continuous_reference_panel)
continuous_analyzer.predict(continuous_current_panel)

  unique_id     score  threshold  drift  reference_size  current_size
0   store_A  2.230089   0.285987   True             300            80
1   store_B  0.237029   0.275712  False             300            80

## 4. `CategoricalDriftAnalyzer`: categorical panel

The same lifecycle applies to categorical populations. `store_A` changes and gains a new category; `store_B` keeps its reference proportions.

In [8]:
categorical_reference_panel = pd.DataFrame({
    "unique_id": np.repeat(["store_A", "store_B"], 300),
    "segment": np.r_[
        rng.choice(["low", "high"], 300, p=[0.8, 0.2]),
        rng.choice(["low", "high"], 300, p=[0.4, 0.6]),
    ],
})
categorical_current_panel = pd.DataFrame({
    "unique_id": np.repeat(["store_A", "store_B"], 80),
    "segment": np.r_[
        rng.choice(["low", "high", "new"], 80, p=[0.2, 0.5, 0.3]),
        rng.choice(["low", "high"], 80, p=[0.4, 0.6]),
    ],
})

categorical_analyzer = CategoricalDriftAnalyzer(
    CatDrift(metric="jensen_shannon", n_resamples=300, random_state=42)
).fit(categorical_reference_panel, target_col="segment")
categorical_analyzer.predict(categorical_current_panel)

  unique_id     score  threshold  drift  reference_size  current_size
0   store_A  0.512905   0.089559   True             300            80
1   store_B  0.005968   0.088635  False             300            80

`predict` returns score, threshold, decision, and both sample sizes. Use `score(current)` for distance only or `threshold=None` to avoid classification. Use `TemporalStabilityAnalyzer` instead when the question is whether a series changed regime internally over time.