# Reference-to-current drift detection

`ConDrift` and `CatDrift` compare individual vectors. Their analyzers fit one independent detector per ID in a panel. The current population is supplied explicitly, so no time column or temporal window is required.

In [7]:
import sys
import os
sys.path.append(os.path.abspath("../.."))
import numpy as np
import pandas as pd

from tinyshift.drift import (
    CatDrift,
    CategoricalDriftAnalyzer,
    ConDrift,
    ContinuousDriftAnalyzer,
)

rng = np.random.default_rng(42)

## 1. `ConDrift`: continuous vectors

The normalized Wasserstein score expresses change in units of reference standard deviation. The default permutation test pools reference and current, permutes their labels, and returns a Monte Carlo p-value.

In [8]:
continuous_reference = rng.normal(0.0, 1.0, 500)
continuous_current = rng.normal(1.0, 1.2, 100)

continuous_detector = ConDrift(
    n_resamples=300,
    random_state=42,
).fit(continuous_reference)
continuous_detector.predict(continuous_current)

DriftResult(score=0.9472812345679126, threshold=0.23647992785629932, p_value=0.0033222591362126247, drift=True, reference_size=500, current_size=100)

## 2. `CatDrift`: categorical vectors

Categorical supports are aligned over their union, so a new category contributes to the Jensen–Shannon distance. With logarithm base 2, the distance is bounded between 0 (identical distributions) and 1 (disjoint distributions).

In [9]:
categorical_reference = rng.choice(
    ["free", "standard", "premium"], 500, p=[0.60, 0.30, 0.10]
)
categorical_current = rng.choice(
    ["free", "standard", "premium", "enterprise"],
    100,
    p=[0.20, 0.35, 0.25, 0.20],
)

categorical_detector = CatDrift(
    n_resamples=300,
    random_state=42,
).fit(categorical_reference)
categorical_detector.predict(categorical_current)

DriftResult(score=0.4300521906958093, threshold=0.13474345846648994, p_value=0.0033222591362126247, drift=True, reference_size=500, current_size=100)

## 3. `ContinuousDriftAnalyzer`: continuous panel

Each current ID is compared only with its own fitted reference population. Here `store_A` shifts while `store_B` remains stable.

In [10]:
continuous_reference_panel = pd.DataFrame({
    "unique_id": np.repeat(["store_A", "store_B"], 300),
    "y": np.r_[rng.normal(0, 1, 300), rng.normal(10, 2, 300)],
})
continuous_current_panel = pd.DataFrame({
    "unique_id": np.repeat(["store_A", "store_B"], 80),
    "y": np.r_[rng.normal(2.5, 1, 80), rng.normal(10, 2, 80)],
})

continuous_analyzer = ContinuousDriftAnalyzer(
    ConDrift(n_resamples=300, random_state=42)
).fit(continuous_reference_panel)
continuous_analyzer.predict(continuous_current_panel)

,unique_id,score,threshold,p_value,drift,reference_size,current_size
0,store_A,2.230089,0.287246,0.003322,True,300,80
1,store_B,0.237029,0.274226,0.086379,False,300,80

## 4. `CategoricalDriftAnalyzer`: categorical panel

The same lifecycle applies to categorical populations. `store_A` changes and gains a new category; `store_B` keeps its reference proportions.

In [11]:
categorical_reference_panel = pd.DataFrame({
    "unique_id": np.repeat(["store_A", "store_B"], 300),
    "segment": np.r_[
        rng.choice(["low", "high"], 300, p=[0.8, 0.2]),
        rng.choice(["low", "high"], 300, p=[0.4, 0.6]),
    ],
})
categorical_current_panel = pd.DataFrame({
    "unique_id": np.repeat(["store_A", "store_B"], 80),
    "segment": np.r_[
        rng.choice(["low", "high", "new"], 80, p=[0.2, 0.5, 0.3]),
        rng.choice(["low", "high"], 80, p=[0.4, 0.6]),
    ],
})

categorical_analyzer = CategoricalDriftAnalyzer(
).fit(categorical_reference_panel, target_col="segment")
categorical_analyzer.predict(categorical_current_panel)

,unique_id,score,threshold,p_value,drift,reference_size,current_size
0,store_A,0.682266,0.133843,0.001996,True,300,80
1,store_B,0.027353,0.108612,0.676647,False,300,80

## 5. Joint-structure drift through PCA reconstruction errors

`ConDrift` accepts a one-dimensional vector. To monitor a relationship between features, fit `PCAReconstructionError` on one part of the reference and compare reconstruction errors from a held-out reference part with errors from the current batch. The same fitted `RobustGaussianScaler` and PCA transform both comparison batches. Holding out reference observations avoids comparing in-sample PCA errors with out-of-sample current errors.

Here both features have similar marginal distributions across batches, while their relationship changes from positive to negative. PCA learns the reference relationship and yields larger errors for the current batch. `ConDrift` tests whether the error distribution changed.

In [12]:
from tinyshift.preprocessing import RobustGaussianScaler
from tinyshift.outlier import PCAReconstructionError

example_rng = np.random.default_rng(7)
reference_x1 = example_rng.normal(size=400)
current_x1 = example_rng.normal(size=120)
reference_x2 = reference_x1 + example_rng.normal(scale=0.15, size=400)
current_x2 = -current_x1 + example_rng.normal(scale=0.15, size=120)

X_reference = np.column_stack([reference_x1, reference_x2])
X_current = np.column_stack([current_x1, current_x2])

X_fit, X_reference_holdout = X_reference[:250], X_reference[250:]
scaler = RobustGaussianScaler().fit(X_fit)
fit_scaled = scaler.transform(X_fit)
reference_scaled = scaler.transform(X_reference_holdout)
current_scaled = scaler.transform(X_current)

pca_error = PCAReconstructionError(n_components=1).fit(fit_scaled)
reference_errors = pca_error.decision_function(reference_scaled)
current_errors = pca_error.decision_function(current_scaled)

error_drift = ConDrift(n_resamples=300, random_state=42).fit(reference_errors)
error_drift.predict(current_errors)

DriftResult(score=132.49974169032606, threshold=0.26589877263396966, p_value=0.0033222591362126247, drift=True, reference_size=150, current_size=120)

This tests **drift in reconstruction errors**. Changes within the retained PCA subspace may leave these errors unchanged. Winsorization also clips values outside bounds learned from the fitting reference, so tail-only shifts may be less visible; use a scaler without clipping when tail changes are the monitoring target. Use `p_value` and `drift` for the decision; `score` is the normalized Wasserstein distance between error samples.

`predict` always runs permutation inference and returns the internal distance, critical threshold, p-value, decision, and both sample sizes. Use `TemporalStabilityAnalyzer` when the question is whether a series changed regime internally over time.